# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac2ce79824015fc3a676a92a4827373fc4bb444b21a8a46f285dedb86d2d90fd248dc8b7601f50e54960ba91cbe0880b6c93885f5e1924fc8cd7b802103ed00d

test:
  secret_key_base: b89dbe8738818f16bcf6e4f0c6ed1705b074e728476d4c24159eb0d4f6156cb345b68d33cc7ecdd8b55d1bb1d3371463a37f1886174b8f2b5284284e6b31b4f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
